### ISSUE TITLE
add utility score to GDA diagram

### ISSUE THREAD

**Issue by yoid2000** [gda-score/code#10]
For this issue, build a method in the gdaPlot.py class that takes as input the python data structure which is output by #8 and draws the appropriate bars and values.

Regarding coverage, the input values should range from 0 to 1. 1 is best, 0 is worst. I suggest for now that you simply make the vertical bar linear with the coverage value. So `coverage=1` results in `height=0.5` and `coverage=0` results in `height=-0.5`. (Or put another way, `height = coverage - 0.5`)

Regarding accuracy, 0 is best, and it gets progressively worse with higher values. Anything above 1 is horrible (means off by 100%). 0.25 is pretty bad (means off by 25%). 0.1 is barely acceptable (off by 10%). 0.05 is not bad, and 0.01 is pretty good.

Given this, the height of the accuracy bar will not be linear with the accuracy value. Please scale the height so that it comes out roughly like this:

coverage | height
--- | ---
0 | 0.5
0.01 | 0.4
0.05 | 0.3
0.1 | 0.1
0.25 | 0
0.5 | -0.25
1 or more | -0.5

The position of the horizontal bar depends on the values of both coverage and accuracy. To compute this position, use the routine `getInterpolatedValue(cov,acc,utilityScore)`, where `cov` is one minus the computed coverage value, `acc` is the computed accuracy value, and `utilityScore` is the list of tuples shown below. You can see an example of this being used in tests/testUtilityScore.py.

```
utilityScore = [
    (1,1,0), (1,.25,0),  (1,.1,0),  (1,.05,0),  (1,.01,0),  (1,0,0),
    (.6,1,0),(.6,.25,.1),(.6,.1,.3),(.6,.05,.4),(.6,.01,.5),(.6,0,.6),
    (.4,1,0),(.4,.25,.2),(.4,.1,.4),(.4,.05,.6),(.4,.01,.7),(.4,0,.8),
    (.2,1,0),(.2,.25,.3),(.2,.1,5), (.2,.05,.7),(.2,.01,.8),(.2,0,.9),
    (.1,1,0),(.1,.25,.4),(.1,.1,.7),(.1,.05,.8),(.1,.01,.9),(.1,0,.95),
    (0,1,0), (0,.25,.5), (0,.1,.75),(0,.05,.9), (0,.01,.95),(0,0,1)
]
```

There should be five colors for the horizontal bar, green, blue, yellow, orange, and red, with red the worst and green the best. Likewise, higher is better for the horizontal bar. We can use the same thresholds to determine color as we currently do for the defense side, which is this (copying from `gdaPlot.py`):

```
    if s['defense'] > 0.9:
        color = 'green'
    elif s['defense'] > 0.7:
        color = 'blue'
    elif s['defense'] > 0.5:
        color = 'yellow'
    elif s['defense'] > 0.3:
        color = 'orange'
    else:
        color = 'red'
```

**Comment by yoid2000** [comment]
Hi @AnirbanGhosh1512 

This is ready for you. Let me know if you have questions.

**Comment by AnirbanGhosh1512** [comment]
Hello Prof. Paul,

I could not find this class "You can see an example of this being used in tests/testUtilityScore.py.", So could you please elaborate me a little bit more to the purpose of use this utilityscore.

Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
My bad. It is there now. Have a look and let me know if you still have
questions.

PF

**Comment by yoid2000** [comment]
You mean the utility score received from `getInterpolatedValue(cov,acc,utilityScore)` in the above image is 0? In that case, of course it should be plotted at -0.5 in the diagram, since -0.5 is the worst score in the diagram, and 0 is the worst score for utility. The same is the case for the defense horizontal bar. 

By the way, if you really plotted that utility bar as zero, then it should be in the middle of the center horizontal line, not on top of it. In other words, the center of the horizontal bar should match the value, not the bottom of the horizontal bar.

**Comment by AnirbanGhosh1512** [comment]
![issue10_updated](https://user-images.githubusercontent.com/33103587/48016783-cda8c300-e12c-11e8-81ec-cadd37ab1dfd.png)

Hello Prof. Paul

Is the attached image as an output ok according to my understanding?

Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
The horizontal curve should be red when at the worst setting. So probably
the blue bar should be red and the red bar should be probably orange...

PF

**Comment by AnirbanGhosh1512** [comment]
![issue10_latest](https://user-images.githubusercontent.com/33103587/48075174-e4115600-e1e2-11e8-89ea-2f7237a1eb1c.png)



Hello Prof. Paul,

I have understood that if the score is 0 then the height of the horizontal bar of utility section should be -0.5 and also the python structure would be updated for color. Like util['utility'] as -0.5 show it can show the color as red. Am I right? If yes then for defense currently we are using static value to test the bar in defense side which result the color as red. 

Is there any other way around to apply for getting the defense score to update the bar color probably orange.

Please see the latest attached image for that.

Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
I'm sorry, but I don't understand your question. Note that the original issue suggests thresholds for the 5 colors.

**Comment by AnirbanGhosh1512** [comment]
Hello Prof. Paul,

Let me make it this way, I got the score 0 for utility so it is -0.5 as horizontal bar position, now according to the code snippet 
        if util['utility'] > 0.9:
            color = 'green'
        elif util['utility'] > 0.7:
            color = 'blue'
        elif util['utility'] > 0.5:
            color = 'yellow'
        elif util['utility'] > 0.3:
            color = 'orange'
        else:
            color = 'red'

if I consider   util['utility']  also -0.5 then it gives the color red.

The same snippet also working for s['defense'] where we initially sending a value 0.2 to get the bar color as Red.

    if s['defense'] > 0.9:
        color = 'green'
    elif s['defense'] > 0.7:
        color = 'blue'
    elif s['defense'] > 0.5:
        color = 'yellow'
    elif s['defense'] > 0.3:
        color = 'orange'
    else:
        color = 'red'

So my question is for utility and for defense whatever value and calculation I am using, is it Ok or I am doing something wrong?

Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
These values should be applied before shifting -0.5.

**Comment by AnirbanGhosh1512** [comment]
![issue10_refined](https://user-images.githubusercontent.com/33103587/48077835-8d0e7f80-e1e8-11e8-9bb3-22b7985f28b0.png)


Hello Prof. Paul,
Is the attached image is fine now? 
Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
It looks ok. What are the pre-shift values of the horizontal bars?

**Comment by AnirbanGhosh1512** [comment]
Hello Prof. Paul,
Currently the pre-shift values for utility is 0, and for defense it is 0.4 as off now. 
Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
offhand the defense bar looks too low if the value if 0.4. That looks more like 0.3 or even less.

**Comment by AnirbanGhosh1512** [comment]
Hello Prof. Paul,

Pardon me for that. It was 0.3 on the negative direction.

Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
Ok, just to be clear. The 0.3 mark (which would be -0.2 in the graph) is where the red mark shows on this image?

![image](https://user-images.githubusercontent.com/2162345/48117427-79efc400-e269-11e8-8906-ea900c7f891f.png)

**Comment by AnirbanGhosh1512** [comment]
Hello Prof. Paul,

Do you mean I need to show the numbers on the bars, like in the red mark I need to show it is -0.2?

Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
No, I just want to verify that that is the location of -0.2 (and not, for instance, the top or bottom edge of the bar)

**Comment by AnirbanGhosh1512** [comment]
![issue10_bar](https://user-images.githubusercontent.com/33103587/48148231-96b3e800-e2b9-11e8-965c-71115a2a40c4.png)



Hello Prof. Paul,

The value is -0.3 and it is goes up as I set some width of the rectangular orange bar. Attached image is for the value -0.2. Mostly the bottom of the bar starts with the value given and goes up till the width set on it.

Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
can you make it so that the horizontal bar is centered on the value, rather than the bottom edge being at the value?

**Comment by AnirbanGhosh1512** [comment]
Hello Prof. Paul,
Yes I can give a try. Will let you know when I finish the job.
Regards,
Anirban Ghosh

**Comment by AnirbanGhosh1512** [comment]
![issue10_fixed](https://user-images.githubusercontent.com/33103587/48150657-9c143100-e2bf-11e8-93f6-a4fa625d1b26.png)


Hello Prof. Paul,
Please see the changes as suggested now it starts from the exact middle. Let me if any further changes required.
Regards,
Anirban Ghosh

**Comment by yoid2000** [comment]
Looks great. Thanks.
