### ISSUE TITLE
Measure and store table characteristics

### ISSUE THREAD

**Issue by yoid2000** [gda-score/code#12]
For a couple of reasons, I'd now like to pre-compute certain characteristics of the columns of each table in our datasets. (We are going to need this for a more efficient utility measure, among other things).

I think I'd like these characteristics for each table to be stored as a separate table in the database at `db001.gda-score.org` (or any other machine where we store raw tables in the future).

Specifically, for every table `tab` in the datasets, I'd like to create another table `tab_char` that contains the characteristics associated with `tab`.

The columns in table `tab_char` should be the following (though we might add more later):

1. `column_name`: the name of the column
2. `column_type`: the type of the column (let's limit to `text`, `int`, `real`, `datetime` for now, which means that you'll have to map the various postgres types to one of these four)
3. `num_rows`: the number of rows in the table (this will be the same for each row of the `tab_char` table)
4. `num_uids`: the number of distinct uids in the table (this will be the same for each row of the `tab_char` table)
5. `num_distinct_vals`: the number of distinct values for column `column_name`
6. `av_rows_per_val`: the average number of rows per distinct value (this is obviously just `num_rows / num_distinct_vals`, and will be the same for every row of the `tab_char` table)
7. `av_uids_per_val`: the average number of distinct uids per distinct value (this is obviously just `num_uids / num_distinct_vals`, and will be the same for every row of the `tab_char` table)
8. `std_rows_per_val`: the standard deviation of the number of rows per value
9. `std_uids_per_val`: the standard deviation of the number of distinct uids per value
10. `max`: the maximum value of the column (this works for text too)
11. `min`: the minimum value of the column

Please write a method that makes these measures, and then creates a file per table that contains the required SQL commands to `CREATE` the table and `INSERT` the appropriate per-column rows.

**Comment by yoid2000** [comment]
Note that issue #15 is an extension of this issue, so it can be done next.

**Comment by srnb** [comment]
The method  generates DBScript per table based on the config parameters mentioned.
Below is the one such example for client table:
@yoid2000 Can you please check and confirm the  datatype choosen for the below columns.
Ex:
create table clients_char  (`column_name` text, `column_type` text, `num_rows` int,`num_uids` int, `num_distinct_vals` int, `av_rows_per_vals` real, `av_uids_per_val` real,`std_rows_per_val` real,`std_uids_per_val` real,`max` text, `min` text, `column_label` text);
insert into clients_char values (uid,int,5369,5369,5369,1.0,1.0,0.0,0.0,13998,1,continuous);
insert into clients_char values (lastname,text,5369,5369,3895,1.3784338896020538,1.3784338896020538,1.9916484879928833,1.9916484879928833,Zych,Aanenson,enumerative);

**Comment by yoid2000** [comment]
These seem fine. 

Please create the folder github:gda-score/code/utility/tools and put it there. Then we can close this issue.

**Comment by srnb** [comment]
committed code changes: utility measure-accuracy,coverage and dbscript:
Sample output: https://gist.github.com/srnb/f7679c432a87af88ed957318fe8815bb
