### ISSUE TITLE
Additional label for `tab_char` information (extension of issue #12)

### ISSUE THREAD

**Issue by yoid2000** [gda-score/code#15]
This is an extension of issue #12

I've come to realize that coverage and accuracy can and should be computed separately. In particular, coverage can probably be computed once per table, whereas there will be many accuracy measures.

Also, I'd like to modify the way I compute coverage somewhat. I want to distinguish between columns that contain "continuous" values and those that don't. A continuous value is one that can sensibly be aggregated numerically, including `real`, some `ints, and `datetime.

For continuous columns, one could say that you don't need to enumerate each value to have it covered. Rather, ranges or histogram buckets can cover continuous columns.  As an example, suppose a K-anonymization scheme aggregates ages into buckets of 10. Even though the individual ages aren't represented, an aggregate of ages 0-9 essentially covers all those ages. The lack of precision can be reflected in the accuracy score.

By contrast, non-continuous columns cannot be covered this way. Non-continuous columns are any `text` column, and some `int` columns (those that enumerate).

I would like to label each column as to whether it is continuous or enumerative. Coverage for continuous and enumerative columns will be computed differently (future issue). Note that it isn't a disaster if we occasionally mis-label a column. In any event, the main purpose of the utility measure is to compare different anonymization algorithms, and any mis-labeled columns will be consistently mis-labeled for all algorithms.

As I said above, all `real` and `datetime` columns are assumed to be continuous. `text` columns are assumed to be enumerative. The difficult case is `int`, which can easily be either. To classify `int`, let's try the following rules:

If there are fewer than 100 distinct values, label it enumerative. Otherwise, do the following:

Build a histogram of 10 buckets, with each histogram counting the number of rows. This can be done with a query of the following form:

```
SELECT floor(col/X)*X, count(*)
FROM table
GROUP BY 1
```

where `X=(max(col)-min(col))/10`

If the bucket with the smallest count is less than 1/2 of the average bucket count, then label the column continuous. Otherwise label the column enumerative.

Add this label to the `tab_char` table from issue #12. You may name the column containing this label as `column_label`.

**Comment by yoid2000** [comment]
@srnb please work on this issue before #14.

**Comment by yoid2000** [comment]
What is the state of this issue? I'd like to upload the tab_char tables...

**Comment by srnb** [comment]
code changes are committed as a part of issue #12
