### ISSUE TITLE
Make birthdate a little more realistic

### ISSUE THREAD

**Issue by yoid2000** [gda-score/code#16]
Sorry to do this, but I'd like you to update the birthdate field so that no birthdate is earlier than 1918.

This doesn't matter for the purpose of creating GDA Scores, but we have to live with these data sets maybe for years, and I can imagine that people will ask over and over why our birthdates are so old. (As it is they may ask my why they aren't distributed realistically, but at least we can fix this one thing.) I should have mentioned this earlier, but I thought it would be ok. I changed my mind.

Hopefully there is some easy `UPDATE` command that just lets you add 100 years to any birthdate ...

**Comment by ku294714** [comment]
Hello sir,

Similar kind of thought ran through my mind. But it was because we also have birthdates of year 2018. Do you want me to update these recent birthdates as well? Or only before 1918 will do?

**Comment by yoid2000** [comment]
birthdates in 2018 are fine. Just get rid of those before 1918...

PF

**Comment by ku294714** [comment]
Hello Sir,

I have updated the birthdates before 1918 as static birthdate=1918-01-01 for raw_banking tables.

However, do you want me to randomize these birthdates because I feel many birthdates with only 1918 values might become more prone to attacks?

Please check raw_bankig tables, if they seem fine to you I can update in similar fashion for other DBs also or else I can assign different DOBs instead of just 1918.

**Comment by yoid2000** [comment]
Of course you should randomize them. 

I think this could have been done much easier by simply adding 100 years to each birthdate earlier than 1918, which is what I suggested in the first place.

But now it is too late to do that, so please randomize them as best you can.

**Comment by yoid2000** [comment]
what do you mean by similar?

**Comment by ku294714** [comment]
I mean raw_banking_l2 has correct set of birthdates and has same data which
is present in the raw_banking tables ( I had messed up the birthdates
column in raw_banking tables, hence created another DB).

Rest all databases are same.

Once you review, I will replace raw_banking with raw_banking_l2

Regards,
Ankit

**Comment by ku294714** [comment]
Yes, sir. I know that point. I think I am not able to convey m point here, can you please check other DBs except raw_banking DB and I can come today and discuss on it?

**Comment by yoid2000** [comment]
I checked raw_census and it is fine. If you believe that the others are fine too, then I'll settle for that.

**Comment by yoid2000** [comment]
yes!
