### ISSUE TITLE
Allow terminate programs with ^C

### ISSUE THREAD

**Issue by yoid2000** [gda-score/code#45]
It has so far always been the case that if a program using gdaAttack crashes (i.e. software error in the code using it), then the software hangs and control-C does not cause it to terminate.

Up to now I've always either had to kill the command window or kill the process.

I've always assumed that the reason for this is that threads are still running so the process doesn't terminate.

It would really be nice if we could end things with control-C.

Ali can you look into this?

**Comment by frzmohammadali** [comment]
issue fixed. termination signal handling is now being implemented in version 2.3.3 to its best possible extend (some delay should be acceptable).
