### ISSUE TITLE
Build dynamic diff priv system using https://github.com/uber/sql-differential-privacy

### ISSUE THREAD

**Issue by yoid2000** [gda-score/code#6]
There is an open source differential privacy tool at:

https://github.com/uber/sql-differential-privacy

It is associated with an Uber/Berkeley research project, and supposedly is the basis for Uber's internal implementation of differential privacy.

I would like to be able to query this system over the RESTful interface built by Rohan.

My intern Ali Reza (alimalik113@gmail.com) has played with this system in the past, so you can talk to him about any issues he had and how to interface the tool with the database. Or you can figure it out yourself, whatever you prefer. 

Basic setup should be:

client <--> server <--> uber_tool <--> database

The databases are on db001.gda-score.org. There are 12 such databases (all starting with `raw_`). I don't know if the uber tool will connect to those or if you'll have to for instance copy them to some other format.

What I'd like you to do is get to the point where a client can send a query to the server and receive an answer back from the server.

The server <--> uber_tool interface is entirely up to you.

Please put the code in `code/anon-methods/uber`

Let me know if you have questions.

**Comment by rbh-93** [comment]
I think I will have to add some code to the uber_tool so that it can handle the sql queries from the simpleServer. Should I make changes in 
sql-differential-privacy/src/main/scala/examples/ElasticSensitivityExample.scala and  
sql-differential-privacy/src/main/scala/examples/QueryRewritingExample.scala only? 

There are other query analyses (in the Analysis Framework) like com.uber.engsec.dp.sql.AbstractAnalysis.analyzeQuery. Do I need to integrate the Analysis Framework also?

**Comment by yoid2000** [comment]
If possible I would like to avoid modifying the uber repository.

Why is it necessary to change the uber repo to recognize sql from simpleServer, versus writing some glue code that gives uber the query syntax it expects?

**Comment by rbh-93** [comment]
For example, the ElasticSensitivityExample.scala  and the QueryRewritingExample.scala at the moment have a static query defined. Now if I send some query from the simpleServer, there is nothing defined in the uber_tool to handle this incoming query. I had one idea of sending the query from simpleServer as a GET request and creating an endpoint in uber_tool to handle this request. But this would mean changing the tool and involves a lot of rework in the uber_tool code as one file may have multiple dependencies. Is there any other way you can suggest?

**Comment by yoid2000** [comment]
How does one currently input a query to the uber thing?

**Comment by rbh-93** [comment]
At the moment  both QueryRewriting and ElasticSensitivity scripts (these are responsible for adding the noise) have only static queries written in the source code. There isn't any implementation of handling queries dynamically. 
As for the Analyses Framework (which analyzes queries based on pre-defined analysis techniques), the method we have to invoke is analyzeQuery.
This analyzeQuery method extends a base class AbstractAnalysis and takes a string containing a SQL statement as an argument.

**Comment by yoid2000** [comment]
How many queries can be placed in the source code?

Does it make sense to just modify the source code file that contains the query with each new query? Would that be the simplest thing to do?

**Comment by rbh-93** [comment]
I took a look at the source code for adding noise and query rewriting. It can run one query at a time and technically you can place any number of queries in the source code and keep them commented. While executing, we can use only the query which is required. This is the quickest and simplest solution at the moment if you don't want to change anything in the tool but not the most optimal one.

**Comment by yoid2000** [comment]
Let's do the simple solution. I guess for each query write it into the file
and execute. I suppose the result is put in some other file? If so then
read this, format, and return.

If it is too painfully slow we can reconsider...

**Comment by rbh-93** [comment]
Which database should I work on and what kind of queries to run? 
"then read this, format, and return." - can you please clarify a bit more?

**Comment by yoid2000** [comment]
The uber tool should be configured to work with 8 databases, those starting
with `raw_`, excluding those ending in `_pub`.

The queries will be submitted by the client (json), passed to the server
which puts it in the file uber expects (sql I presume), executes the uber
code to run the query, and somehow returns the answer back to the client.

I presume there are some limitations on what SQL can be used, but I don't
know what this is ... you'll  have to tell me.

It would be convenient if the answer returned to the client has the same
format as the queries that we currently make on the postgres odbc
interface, which is a list of lists.

For now, could you show me several examples of queries and the
corresponding answers as the uber tool produces them? Then I can tell you
how they should be formatted.

**Comment by rbh-93** [comment]
Thank you for the clarification. I will start working on it.

**Comment by yoid2000** [comment]
ok, good luck. Let me know if you run into any doubts.

**Comment by rbh-93** [comment]
I can go tomorrow afternoon.

**Comment by yoid2000** [comment]
ok see you then

**Comment by yoid2000** [comment]
Is it possible to execute the following SQL query on the Uber system?

```
SELECT col1, col2, count(*)
FROM table
GROUP BY 1,2
```

Well, I notice that the documentation says this:

  * Histogram queries (using SQL's GROUP BY) must be handled carefully so as not to leak information in the bin labels.
  * The analysis throws an error to warn about this, but this behavior can overridden if you know what you're doing.

Hmmmm, I wonder how it can be overridden....

**Comment by yoid2000** [comment]
Or for that matter, can you do any query that shows the column value, even without group by. For instance just this:

```
select col from table
```

**Comment by rbh-93** [comment]
Hi, the task is almost done. The final part I need to do is write the schema of all the 8 raw_ databases into the config file in UBER Tool.  I will run the queries you mentioned and let you know asap. Apart from this there were a few things I want to discuss before pushing the final code to Git. Can we meet tomorrow morning?

**Comment by yoid2000** [comment]
Yes lets meet tomorrow. I should be in by around 10AM. 11AM is a bit more
reliable.

PF

**Comment by rbh-93** [comment]
> Is it possible to execute the following SQL query on the Uber system?
> 
> ```
> SELECT col1, col2, count(*)
> FROM table
> GROUP BY 1,2
> ```
> Well, I notice that the documentation says this:
> 
> * Histogram queries (using SQL's GROUP BY) must be handled carefully so as not to leak information in the bin labels.
> * The analysis throws an error to warn about this, but this behavior can overridden if you know what you're doing.
> 
> Hmmmm, I wonder how it can be overridden....

I ran the following query: "Query sent by client: SELECT account_id, count(*) FROM accounts GROUP BY account_id
Private result: 2850.0"
The exception was: "This query returns a histogram bin column ('account_id') that is not safe for release. The bin labels must be made differentially private, which requires additional data model knowledge. If you know what you're doing, you can disable this message by setting canRelease=true for columns of protected tables that are safe for release, or setting flag [dp.elastic_sensitivity.check_bins_for_release] = false to disable this check."

**Comment by rbh-93** [comment]
> Or for that matter, can you do any query that shows the column value, even without group by. For instance just this:
> 
> ```
> select col from table
> ```

"Query sent by client: SELECT account_id FROM accounts"
Private result: 11382.0
Exception:  "UnsupportedQueryException: This analysis works only on counting queries"

Another small thing I noticed while trying out different queries, aliases are not supported by Uber Tool.

**Comment by rbh-93** [comment]
I have made a folder called sql-differential privacy in gda-score/code and pushed the code there. Please let me know if everything is alright.

**Comment by rbh-93** [comment]
![architecture](https://user-images.githubusercontent.com/30060044/48316369-06d8ab80-e5e3-11e8-98f5-81945371480e.jpg)

This is a diagram to depict the data flow between the Client/Server and Uber Tool.

**Comment by yoid2000** [comment]
shouldn't the simple server be reading the result.txt? (after all, the
client is on a different machine and can't read that file)

**Comment by rbh-93** [comment]
Sorry, my mistake. I corrected it. Here is the new architecture diagram. 
![architecturejpeg](https://user-images.githubusercontent.com/30060044/48359235-ce95a380-e69c-11e8-8801-269c8aa4f1f6.jpg)

**Comment by rbh-93** [comment]
The server sends the query result along with the http response code (200 for OK, 500 for Internal Server Error, etc.) for the request sent by the client. I included that so that in case of any error in connection between client and server we can know what went wrong.  Should I remove that?

**Comment by yoid2000** [comment]
No of course you shouldn't remove it. I just wanted to be clear that both
the data and the response code are sent in the same response, not two
separate responses.

**Comment by rbh-93** [comment]
Yes, the status code is displayed with the queryResult. Not as two separate responses. Please check and let me know if there is anything else you want me to change.
